### PR TITLE
Raleway is basically unusable as a body font

### PR DESCRIPTION
**Pull request by namanyayg**

### CODE REVIEW

**Comment by alfredxing** [comment]
Marking for feedback. Official documentation does say it's a heading font, but that's only because the original font was only in the 100 weight. With the regular (400) weight it does okay (but not optimally).

**Comment by fluke** [comment]
Possibly both? I use it mostly for headings.

**Comment by alfredxing** [comment]
For "both", we usually use the "body" tag. Any other opinions on this?

**Comment by curiositry** [comment]
I don’t like reading body text set in Raleway. Although it’s not a display font exactly, I don’t think it’s use for setting body text should be encouraged. Just my two cents.

**Comment by alfredxing** [comment]
Alright, seems like most of you agree that Raleway is a display font. Merging!

@namanyayg Thanks for the PR!

**Pull request merged**
