### PR TITLE
Add SVG font support

### PR DESCRIPTION
**Pull request by alfredxing**
In the beginning (well before launch), Brick had SVG font support. I don't quite remember why I got rid of it (I think it was because of space), but due to some persistent problems with OTF & TTF font rendering in Chrome on Windows, we might be bringing this back.

The PR adds support for an `s` flag, that triggers a media query to target Webkit browsers (beware: this includes  browsers on OS X as well). The SVG fonts are, of course, also included.

Addresses (or at least attempts to) #79.

### CODE REVIEW

**Comment by fluke** [comment]
Is space currently an issue? @alfredxing

**Comment by alfredxing** [comment]
@kartikluke Not really. According to GitHub, we're at about 170 MB. It's more about the relative size of the SVGs compared to the WOFFs: where the EB Garamond WOFF weighs in at around 222KB (quite large already), the SVG weighs in at 1.8MB (huge for a font file. We can gzip the files beforehand, which should help.

**Comment by fluke** [comment]
Yeah that does seem rather large. But it has its use. Keeping it optional is the best way to go about it.

**Comment by alfredxing** [comment]
Merging! If anyone has any issues whatsoever, please please open up an issue.
@kartikluke Thanks for your work on this!

**Pull request merged**
