### PR TITLE
Add Encode Sans Complete Font Family

### PR DESCRIPTION
**Pull request by dfrankland**
Encode
Some letters have abrupt asymmetrical curves, while other are soft and
fluid.
This contrasting combination allows for a pleasant modern feeling,
without being squarish, boring or repetitive.
Obsessively optimized for the web in all proportions and details.

What started as a single style font, is now becoming a 45 styles
super-family.

We are doing 5 widths:
Compressed, Condensed, Narrow, Normal and Wide
Each one in 9 weights:
Thin, ExtraLight, Light, Regular, Medium, SemiBold, Bold, ExtraBold and
Black

We hope that this ample range of Widths and Weights will provide web
designers with lots of possibilities for creating stunning layouts.

Project Members: PabloImpallari, AndresTorresi

http://www.impallari.com/projects/overview/encode

### CODE REVIEW

**Comment by alfredxing** [comment]
Awesome, thanks!

**Comment by dfrankland** [comment]
Awesome :+1: Thank you for this entire service!

**Comment by dfrankland** [comment]
Woops I closed this lol

**Comment by alfredxing** [comment]
Sorry for the super long delay, I've been quite busy the past few months.

I'm not so sure about adding the Narrow and Wide versions, since they would have very limited use on the web. What do you think?

Also, I don't think we are supporting SVG anymore (#102), so you can get rid of those. :smile:

**Pull request closed without merging**
