### PR TITLE
added sample css and html5 page for previewing fonts from H1->H6 and 8pt...

### PR DESCRIPTION
**Pull request by priyatam**
Great work, thanks so much!

I added a sample typography base.css and an HTML5 page for previewing various font sizes and pts (8pt to 72pt) in a static html (without php). Hope it's useful.

### CODE REVIEW

**Comment by alfredxing** [comment]
Thanks!
What would this page be used for (i.e. what is its purpose)?

**Comment by priyatam** [comment]
Currently, I can't preview the sizes/pts of the fonts in your catalogue without setting up an html page. The provided [index.html](http://priyatam.github.io/brick/) is a start for developers, like me, interested in configuring web fonts in css3.

**Comment by alfredxing** [comment]
True, but it only previews one font at a time. This is already achieved with the [preview page](http://brick.im/preview/brick.html) (albeit not as diversely).

**Comment by priyatam** [comment]
As a Web font provider, are you interested in supporting CSS3 or [Responsive Web Typography](http://simplefocus.com/flowtype/)? If not, my mistake.

**Comment by alfredxing** [comment]
Of course I'm interested in supporting CSS3. I just don't quite understand how this would help in a significant way.

**Comment by alfredxing** [comment]
If you want, you can integrate this into the preview pages at `[gh-pages]/preview` and resubmit. Closing this for now.

**Pull request closed without merging**
