### PR TITLE
Added Andada

### PR DESCRIPTION
**Pull request by AlessioLaiso**
Added Andada 400, 400i, 700, 700i.
What about Andada Small Caps?

### CODE REVIEW

**Comment by alfredxing** [comment]
Thanks! I'm confused about the `SOURCE` file, though. It links to the Andanda HT Pro page, which isn't free (and definitely not licensed under SIL). The file should link to where _you_ got the original font files (the free ones).

**Comment by AlessioLaiso** [comment]
Ok, I have fixed that.
By the way, I've noticed that this same exact issue applies to the font Bitter. It may have to be fixed too.

**Comment by alfredxing** [comment]
Actually, the page linked to for Bitter is actually the page about Bitter—the open source version. If you click on the "Download" banner on the left, it'll tell you that it's licensed under the OFL.

Also, It'll be preferred if the fonts were taken from the source available in Google Fonts' repository, instead of from FontSquirrel (since we don't know where they get their fonts from):
http://googlefontdirectory.googlecode.com/hg/ofl/andada/src/

If you can't open the `.vfb` files, I can process them and add them.

Thanks!

**Comment by AlessioLaiso** [comment]
You are right about Bitter. Sorry.

I can't open .vfb files now, so I have generated new .woff files from the source .sfd files using FontForge. I hope that is ok.

**Comment by alfredxing** [comment]
Should be fine. I'll merge the commits, and you can test the font out on a page. Tell me if there's any problems with them!

Thanks again for contributing!

**Comment by AlessioLaiso** [comment]
Ok, I'll let you know!
You're welcome :)

**Pull request merged**
