### PR TITLE
Cormorant 2.0

### PR DESCRIPTION
**Pull request by phoenixenero**
> Cormorant is a free display type family developed by Christian Thalmann ([Catharsis Fonts](https://www.myfonts.com/foundry/Catharsis_Fonts)).  It comprises a total of 45 font files spanning 9 different styles (Roman, Italic, Infant, Infant Italic, Garamond, Garamond Italic, Upright Cursive, Small Caps, Unicase) and 5 weights (Light, Regular, Medium, Semibold, Bold).  For an illustrated presentation and description of the family, **please visit [its Bēhance page](https://www.behance.net/gallery/28579883/Cormorant-an-open-source-display-font-family)**.

From the [Cormorant Github page](https://github.com/CatharsisFonts/Cormorant).

a0389328579883 55c877c0e7701

I may plan on converting the other families. It's a very extensive type system!

### CODE REVIEW

**Comment by alfredxing** [comment]
Thanks! Before I merge, can you please rebase/squash the middle 2 commits? They're basically undoing each other, which might become confusing later on when people are looking at commit history.

**Comment by phoenixenero** [comment]
Alrighty then!

**Comment by phoenixenero** [comment]
Done! I re-did everything and forced pushed it.

**Comment by alfredxing** [comment]
Thanks!

**Pull request merged**
