### PR TITLE
Fix link to catalogue

### PR DESCRIPTION
**Pull request by bsdlp**
ideally the catalog page should just be automatically generated from the catalog? Anyways, cat.json was removed in eb85f80159a84125d78bc680f7fef2dba58df58f

### CODE REVIEW

**Comment by alfredxing** [comment]
That would be ideal, yes, but the site is hosted on GitHub Pages and I can't think of a way to do this in Jekyll...

**Comment by hnrch02** [comment]
Maybe [use Jekyll's data files](http://jekyllrb.com/docs/datafiles/) for this.

**Comment by alfredxing** [comment]
@hnrch02 That would be pretty cool, though you'd need to update both the data file and the `index.php` file.

**Comment by hnrch02** [comment]
Or read the file's content from the disk as you did with the JSON file. As I understand it, PHP has native support for parsing YAML?

**Comment by alfredxing** [comment]
@hnrch02 Possible, but disk reads are costly (that's why I moved the data into the PHP file). It's also a bit more complicated since the data file would be on a different branch (`[gh-pages]` instead of `[master]`).

**Comment by alfredxing** [comment]
@hnrch02 You can create a new issue if you feel like it, since this one is marked as closed and can't be reopened (it's a pull request).

**Pull request merged**
